baseURL: "https://Fadyio.com"
languageCode: en-us
theme: ["hugo-notice", "hugo-redirect"]
paginate: 5
title: "Fady Nagh"
copyright: "© 2022  Fady Nagh"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
googleAnalytics: "G-1ZN2JNL2H3"
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors:
  - error-remote-getjson
minify:
  disableXML: true
  minifyOutput: true
##################################################################
params:
  env: production
  assets:
    disableHLJS: true
    disableFingerprinting: false
    favicon: /favicon/favicon.ico
    favicon16x16: /favicon/favicon-16x16.png
    favicon32x32: /favicon/favicon-32x32.png
    apple_touch_icon: /favicon/apple-touch-icon.png
    safari_pinned_tab: /favicon/mstile-144x144.png
  images:
    - /img/social.jpg # This is the root pic when sharing on social media
  label:
    text: Fadyio.com # sets the top left blue "home" link text
  homeInfoParams:
    Title: "Hi there \U0001F44B\U0001F3FB"
    Content: "Welcome to the website of Fady Nagh. Views and typos are my own."
  socialIcons:
    - name: github
      url: https://github.com/Fadyio
    - name: linkedin
      url: https://www.linkedin.com/in/Fadyio
    - name: twitter
      url: https://twitter.com/Fady_io
    - name: stackoverflow
      url: https://stackoverflow.com/users/14895864
    - name: email
      url: mailto:Fady@Fadyio.com
    - name: rss
      url: https://Fadyio.com/index.xml
  author: "Fady Nagh"
  description: "A collection of walkthroughs, rants, and hacks on emerging cloud technologies and DevOps methodology and tools."
  comments: true
  mainSections:
    - post
    - posts
  keywords: [DevOps, Fady Nagh, Cloud, Linux, tech, Blog, Golan, AWS, docker, kubernetes, Ansible]
  defaultTheme: auto
  ShowBreadCrumbs: true
  disableThemeToggle: false
  ShowPostNavLinks: true
  DateFormat: "2006-01-02"
  ShowShareButtons: true
  disableAnchoredHeadings: true
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  TocOpen: false
  disableScrollToTop: true
  ShowRssButtonInSectionTermList: false
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    responsiveImages: true
  schema:
    publisherType: Website
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 2
    keys: ["title", "content"]
  privacy:
    disqus:
      disable: true
    googleAnalytics:
      disable: true
    instagram:
      disable: false
      simple: true
    twitter:
      disable: false
      enableDNT: false
      simple: true
    vimeo:
      disable: false
      simple: true
    youtube:
      disable: false
      privacyEnhanced: true
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    noClasses: false
    lineNos: false
    style: dracula
menu:
  main:
    - name: Blog
      url: /posts/
      weight: 1
    - name: About
      url: about
      weight: 1
    - name: Projects
      url: projects
      weight: 3
    - identifier: categories
      name: Series
      url: /categories/
      weight: 4
    - name: Contact
      url: /contact/
      weight: 5
    - post: <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-list-search" width="25" height="25" viewBox="0 0 24 20" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"> <path stroke="none" d="M0 0h24v24H0z" fill="none"/> <circle cx="15" cy="15" r="4" /> <path d="M18.5 18.5l2.5 2.5" /> <path d="M4 6h16" /> <path d="M4 12h4" /> <path d="M4 18h4" /> </svg>
      url: /search/
      weight: 6
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary for search to work
