baseURL: "https://Fadyio.com"
languageCode: en-us
title: Fady Nagh
paginate: 5
theme: "Blog"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
minify:
  disableXML: true
  minifyOutput: true
params:
  TocSide: 'right' # or 'right'
  description: "Fady Nagh's Blog"
  keywords: [DevOps, Blog, Golan, AWS, docker, kubernetes, Ansible]
  author: Fady
  defaultTheme: auto # dark, light
  EnableInstantClick: true
  env: production
  googleAnalytics: G-1ZN2JNL2H3
  DateFormat: "2006-01-02"
  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["linkedin", "twitter"]
  ShowWordCount: true
socialIcons:
  - name: twitter
    url: "https://twitter.com/fady_io"
  - name: stackoverflow
    url: "https://stackoverflow.com"
  - name: github
    url: "https://github.com/fadyio"
menu:
  main:
    - name: Blog
      url: /posts/
      weight: 1
    - name: Tags
      url: /tags/
      weight: 4
    - name: Archive
      url: /archives/
      weight: 5
