name: Image Optimizer
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Convert image files
      run: |
        find . -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) -exec sh -c 'cwebp -q 80 "$0" -o "${0%.*}.webp"' {} \;

    - name: Delete the original image files
      run: |
        find . -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) -exec rm {} \;

    - name: Replace references in Markdown
      run: |
        find . -type f -name "*.md" -exec sed -i 's/\.png/\.webp/g' {} +
